project:
  type: website
  output-dir: docs

website:
  title: "Arash"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Publications
    right:
      - icon: github
        href: https://github.com/arashabadi
      - icon: linkedin
        href: https://linkedin.com/in/arashbagherabadi
      - icon: twitter
        href: https://twitter.com/arash_b_abadi

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    code-fold: true
    code-tools: true
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true

execute:
  freeze: auto 