project:
  type: website
  output-dir: docs

website:
  title: "Arash Bagherabadi"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/arashabadi
      - icon: linkedin
        href: https://linkedin.com/in/arashbagherabadi
      - icon: twitter-x
        href: https://x.com/arash_b_abadi

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: theme-toggle.html
    toc: false
    code-fold: true
    code-tools: true
    self-contained: true
    link-external-icon: true
    link-external-newwindow: true

execute:
  freeze: auto
